Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/produce_items', to: 'produce_items#index'
  get '/produce_items/:id', to: 'produce_items#show'
  get '/farmers_market_stands/:farmers_market_stand_id/produce_items', to: 'farmers_market_stand_produce_items#index'
  get '/farmers_market_stands', to: 'farmers_market_stands#index'
  get '/farmers_market_stands/new', to: 'farmers_market_stands#new'
  post '/farmers_market_stands/new', to: 'farmers_market_stands#new'
  post '/farmers_market_stands', to: 'farmers_market_stands#create'
  get '/farmers_market_stands/:id/edit', to: 'farmers_market_stands#edit'
  patch '/farmers_market_stands/:id', to: 'farmers_market_stands#update'
  get '/farmers_market_stands/:id', to: 'farmers_market_stands#show'
  get '/farmers_market_stands/:id/produce_items/new', to: 'farmers_market_stand_produce_items#new'
  post '/farmers_market_stands/:id/produce_items', to: 'farmers_market_stand_produce_items#create'
  get '/produce_items/:id/edit', to: 'produce_items#edit'
  patch '/produce_items/:id', to: 'produce_items#update'
  get '/dealerships', to: 'dealerships#index'
  get '/dealerships/new', to: 'dealerships#new'
  get '/dealerships/:id', to: 'dealerships#show'
  get '/dealerships/:dealership_id/cars', to: 'dealership_cars#index'
  get '/cars', to: 'cars#index'
  get '/cars/:id', to: 'cars#show'
  post '/dealerships', to: 'dealerships#create'
  get '/dealerships/:id/edit', to: 'dealerships#edit'
  patch '/dealerships/:id', to: 'dealerships#update'
  get '/dealerships/:id/cars/new', to: 'dealership_cars#new'
  post '/dealerships/:id/cars', to: 'dealership_cars#create'
  get '/cars/:id/edit', to: 'cars#edit'
  patch '/cars/:id', to: 'cars#update'
  # get '/dealerships/:id/cars/sort', to: 'dealership_cars#sort'
end
